### ISSUE TITLE
Support exclusion of publications, better parsing of bibstems

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/tugboat#62]
The selection/deselection of publications from the ADS Classic form currently does not handle correctly the case where one wants to exclude one or more journals.  These are the cases we need to handle:

1. Exclude one publication (e.g. "-AAS")
2. Exclude multiple publications (e.g. "-AAS, -arXiv")
3. Have a mix of include/exclude (e.g. "arxiv, -AAS, EPJWC")

Case 1 is currently translated as `bibstem:("-AAS")` rather than `bibstem:(-"AAS")` (which does the opposite selection), so this needs fixing

For case 2, having just a negative query will not work: (`bibstem:(-"AAS" or "-arXiv")` returns 0 records).  I suggest we simply move the `-` sign outside of the bibstem and concatenate the bibstems like so: `-bibstem:("AAS" or "arXiv")`.  An alternative (but more expensive) way that seems to work is to introduce a wildcard inside the bibstem field selection: `bibstem:(* -"AAS" -"arXiv")`

For case 3, we would need to group the include ones then subtract the exclude ones: `bibstem:("AAS" or "EPJWC" -"AAS")` (although I think order does not matter if we use all "ors")

Finally, there is a bug in parsing multiple bibstems: if one enters "AAS, arXiv" (note the space) then the BBB query becomes `bibstem:("AAS" OR " arXiv")`.  We should strip the extra space before "arXiv".

**Comment by golnazads** [comment]
To make it easier on the logic I was wondering if we could group positive and negative separately (Case 3), and so no matter how many positive and negative we have, have two statements, like
`bibstem:("AAS" or "EPJWC") and -bibstem("AAS")` and for Case 2 go with -bibstem:("AAS" or "arXiv") which would fall nicely with Case 3. Would that be OK?

**Comment by aaccomazzi** [comment]
Yes, that would work and is fine with me.  BTW, generally people will choose just selection or deselection, because mixing the two rarely makes sense (if you select just one journal you are deselecting everything else).  But to be complete we have to take into account the cases where one can select via wildcard and then deselect more specific content.

**Comment by golnazads** [comment]
Implemented in release v2.0.12.
